---

- hosts: web
  become: yes
  tasks:
  -  name: Install bind on Ubuntu
     apt:
        name=bind9
        state=latest
     notify:
        bind9 systemd
  handlers:
  - name: bind9 systemd
    systemd:
     name: bind9.service
     enabled: yes
     state: started
